In [1]:
import numpy as np
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [2]:
b = np.array([[1,2,3], [4,5,6]]) # これで2-dimensional array(2次元配列)
b.T # 転置

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
a.T # a.ndim < 2なので変化なし。

array([1, 2, 3])

In [4]:
a.data # メモリの位置を示す。

In [5]:
a.dtype

dtype('int64')

In [6]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [7]:
a.flat[1] # aを１次元配列にしたときの1番目の要素を表示。

2

In [8]:
b.flat[4] # bを１次元配列にしたときの4番目の要素を表示。

5

In [9]:
c = np.array([1.-2.6j, 2.1+3.J, 4.-3.2j]) # 複素数を要素とするndarrayインスタンスを生成
c

array([1. -2.6j, 2.1+3. j, 4. -3.2j])

In [10]:
c.real # 実部

array([1. , 2.1, 4. ])

In [11]:
c.imag # 虚部

array([-2.6,  3. , -3.2])

In [12]:
b.size

6

In [13]:
a.itemsize # バイトオーダーでの要素１つ１つの長さ

8

In [14]:
c.size, c.itemsize # cの方がsizeにたいしてitemsizeが大きくなる。

(3, 16)

In [15]:
a.nbytes # バイトオーダーでの配列の長さ

24

In [16]:
a.size * a.itemsize == a.nbytes # この等式が成り立つ

True

In [17]:
a.ndim # 次元数

1

In [18]:
b.ndim

2

In [19]:
a.shape # 形状

(3,)

In [20]:
b.shape # 形状

(2, 3)

In [21]:
d = np.array([[[2,3,2],[2,2,2]],[[4,3,2],[5,7,1]]]) # 3次元配列を生成
d.shape, d.ndim # 形状を次元数を表示

((2, 2, 3), 3)

In [22]:
a.strides # 各次元方向(axis=ndim, axis=ndim-1,...,axis=1, axis=0)における１つの要素に移動するためのバイトオーダーでの距離

(8,)

In [23]:
b.strides # .ndim = 2

(24, 8)

In [24]:
c.strides # .ndim = 3

(16,)

In [25]:
d.strides # .ndim = 3

(48, 24, 8)

In [26]:
# 次は.ctypesと.baseです。.ctypesはctypesモジュールを使った操作を行うためのイテレータとなります。
# .baseはこの配列がビューであるならビューをしている元の配列を示します。

a.ctypes.data # ctypesモジュールを使った操作。

140527946327664

In [27]:
a.base # aのベースとなる配列はどこか。

In [28]:
e = a[:2]

In [29]:
e.base

array([1, 2, 3])

In [30]:
e.base is a

True

In [31]:
a.base is e.base

False

In [32]:
a = np.random.randn(100,100)
b = np.array(a, order ='C') # row-major
c = np.array(a, order ='F') # column-major

In [33]:
b.strides, c.strides # ストライドを見ると、距離が逆転している。  

((800, 8), (8, 800))

In [34]:
np.allclose(b, c) # 配列の要素が全部一致しているか確認

True

In [35]:
x = np.ones((100000,))
x

array([1., 1., 1., ..., 1., 1., 1.])

In [36]:
y = np.ones((100000*100,))[::100] # 100個飛ばしに読み込む
y

array([1., 1., 1., ..., 1., 1., 1.])

In [37]:
x.strides # 1つ隣の要素にたどり着くために8バイト分ジャンプするだけでいい。

(8,)

In [38]:
y.strides # 1つ隣の要素にたどり着くために800バイト分ジャンプする必要がある。

(800,)

In [39]:
x.shape, y.shape

((100000,), (100000,))

In [40]:
%timeit x.sum() # こちらの方が断然早い

30.3 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [41]:
%timeit y.sum()

1.35 ms ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [42]:
y_copy = np.copy(np.ones((100000*100,))[::100])

In [43]:
y_copy.strides

(8,)

In [44]:
%timeit y_copy.sum()

29.2 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [45]:
a = np.array([1,2,3])
b = np.array([[1,1,1],[2,4,1]]) # ２次元配列
b + a

array([[2, 3, 4],
       [3, 6, 4]])